### PR TITLE
Bigquery repeated data type

### LINKED ISSUE #190: Incorrect `data_type` for BigQuery `REPEATED` fields
### Describe the bug
BigQuery supports arrays as [REPEATED fields](https://cloud.google.com/bigquery/docs/nested-repeated#define_nested_and_repeated_columns)
Running generate_model_yaml for a model with a repeated field of a certain datatype will result in a 
schema with `data_type: datatype` rather than `data_type: array<datatype>`
Running the model again with `contract.enforced=true` will show the error:

   column_name  | definition_type | contract_type | mismatch_reason    |
   ------------ | --------------- | ------------- | ------------------ |
   repeated_int | ARRAY\<INT64>    | INT64         | data type mismatch |

Repeated records should have `data_type: array`

### Steps to reproduce
create a model_with_repeated_field.sql:
```sql
select 
    [1,2,3,4] as repeated_int
```
run it
```bash
$ dbt run -s model_with_repeated_field -f
```
### Expected results
```yml
version: 2

models:
  - name: model_with_repeated_field
    description: ""
    columns:
      - name: repeated_int
        data_type: array<int64>
        description: ""
```

### Actual results
```yml
version: 2

models:
  - name: model_with_repeated_field
    description: ""
    columns:
      - name: repeated_int
        data_type: int64
        description: ""
```

### Screenshots and log output
Running the model with the following yml:
```yml
models:
  - name: model_with_repeated_field
    config:
      contract:
        enforced: true
    columns:
      - name: repeated_int
        data_type: int64
        description: ""
```
Screenshot 2024-11-12 at 16 32 13

### System information
```yml
packages:
  - package: dbt-labs/codegen
    version: 0.12.1
  - package: dbt-labs/dbt_utils
    version: 1.1.1
```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
Core:
  - installed: 1.8.8
  - latest:    1.8.8 - Up to date!

Plugins:
  - bigquery: 1.8.3 - Up to date!
```

**The operating system you're using:**
MacOS Sequoia Version 15.1

**The output of `python --version`:**
Python 3.10.15

### Additional context
generate_model_yaml gets the data_type using `data_type_format_model`
```jinja2
    {% if include_data_types %}
        {% do model_yaml.append('        data_type: ' ~ codegen.data_type_format_model(column)) %}
    {% endif %}
```
which in turn calls codegen.format_column
```jinja2
{% macro data_type_format_model(column) -%}
  {{ return(adapter.dispatch('data_type_format_model', 'codegen')(column)) }}
{%- endmacro %}

{# format a column data type for a model #}
{% macro default__data_type_format_model(column) %}
    {% set formatted = codegen.format_column(column) %}
    {{ return(formatted['data_type'] | lower) }}
{% endmacro %}
```
format_column is vendored in macros/vendored/dbt_core/format_column.sql
But it doesn't handle the specific case for repeated fields.

I am tempted to create a `default__format_column` and a `bigquery__format_column` to handle BigQuery specifically:

```jinja2
{% macro format_column(column) -%}
  {{ return(adapter.dispatch('format_column', 'codegen')(column)) }}
{%- endmacro %}

{% macro default__format_column(column) -%}
  {% set data_type = column.dtype %}
  {% set formatted = column.column.lower() ~ " " ~ data_type %}
  {{ return({'name': column.name, 'data_type': data_type, 'formatted': formatted}) }}
{%- endmacro -%}

{% macro bigquery__format_column(column) -%}
  {% if column.mode.lower() == "repeated" %}
    {% set data_type = "array" if column.dtype.lower() == "record" else "array<" ~ column.dtype ~ ">" %}
  {% else %}
    {% set data_type = column.dtype %}
  {% endif %}
  {% set formatted = column.column.lower() ~ " " ~ data_type %}
  {{ return({'name': column.name, 'data_type': data_type, 'formatted': formatted}) }}
{%- endmacro -%}
```
and moving it all into helpers.sql while removing the vendored format_column

Alternatively, bigquery__format_column could return a `'mode': column.mode` field 
and the adapter specific datatype conversion would be taken care of in 
`bigquery__data_type_format_model` and `bigquery__data_type_format_source`

### Are you interested in contributing the fix?
Yes. I would like some input on whether the proposed solution in Additional context is reasonable.

### PR DESCRIPTION
**Pull request by Thrasi**
resolves #190

This is a:
- [X] bug fix with no breaking changes

## Description & motivation

Separate `format_column` macro into `default__format_column` and  `bigquery__format_column` to handle BigQuery REPEATED fields.

## Checklist
- [X] This code is associated with an issue which has been triaged and [accepted for development](https://docs.getdbt.com/docs/contributing/oss-expectations#pull-requests). 
- [X] I have verified that these changes work locally
- [x] I have updated the README.md (if applicable)
- [X] I have added tests & descriptions to my models (and macros if applicable)
- [x] I have added an entry to CHANGELOG.md

### CODE REVIEW

File: macros/vendored/dbt_core/format_column.sql [hunk 1]
```diff
@@ -1,5 +1,21 @@
...
+{# Vendored from: https://github.com/dbt-labs/dbt-bigquery/blob/4d255b2f854d21d5d8871bdaa8d7ab47e7e863a3/dbt/include/bigquery/macros/utils/get_columns_spec_ddl.sql#L1-L5 #}
+{# But modified to handle https://github.com/dbt-labs/dbt-codegen/issues/190 #}
+{% macro bigquery__format_column(column) -%}
+  {% set data_type = column.data_type %}
+  {% if column.mode.lower() == "repeated" and column.dtype.lower() == "record" %}
+    {% set data_type = "array" %}
+  {% endif %}
+  {% set formatted = column.column.lower() ~ " " ~ data_type %}
+  {{ return({'name': column.name, 'data_type': data_type, 'formatted': formatted}) }}
+{%- endmacro -%}
```
Comment (dbeatty10) [inline macros/vendored/dbt_core/format_column.sql:21]: Adding trailing newline:

```suggestion
{%- endmacro -%}

```

This will remove this red icon from the diff:

image

**Review by dbeatty10 — COMMENTED** [review]
@Thrasi this looks good to me!

Once you flip this to "ready to review", then we can give final approval and then merge.

Heads-up: Tomorrow will be my last day in the office before I'll be one holiday for a few weeks. If we can get it merged tomorrow, then great. Otherwise, I can pick it back up again when I return.

**Comment by Thrasi** [comment]
I'm not sure how the process for [updating the CHANGELOG.md](https://github.com/dbt-labs/dbt-codegen/blob/main/CONTRIBUTING.md#adding-changelog-entry) but this was my attempt

File: CHANGELOG.md [hunk 2]
```diff
@@ -1,3 +1,7 @@
+### Fixes
+
+- fix data_type for BigQuery repeated fields
+
```
Comment (dbeatty10) [inline CHANGELOG.md:4]: Per https://github.com/dbt-labs/dbt-codegen/issues/238, we don't need to do this anymore, so I'm going to peel it out.

Then when this feature is included in the next release of codegen, we'll update the changelog as-needed.

```suggestion
### Fixes

- fix data_type for BigQuery repeated fields

```

**Review by dbeatty10 — APPROVED** [review]
Thanks for your work on this @Thrasi !

**Comment by dbeatty10** [comment]
> I'm not sure how the process for [updating the CHANGELOG.md](https://github.com/dbt-labs/dbt-codegen/blob/main/CONTRIBUTING.md#adding-changelog-entry) but this was my attempt

Contributors don't need to manually update the CHANGELOG anymore, so I just pulled it out.

We've got a couple issues opened to update the PR template and contributing guide to remove those pieces so it isn't confusing in the future: https://github.com/dbt-labs/dbt-codegen/issues/238 and https://github.com/dbt-labs/dbt-codegen/issues/237
